services:
  mysql:
    image: mysql:8.0
    container_name: sdb-12-02-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sakila
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    command:
      - --default-authentication-plugin=caching_sha2_password
      - --local-infile=1

volumes:
  mysqldata:
