SELECT
  k.TABLE_NAME    AS `Название таблицы`,
  k.COLUMN_NAME   AS `Название первичного ключа`
FROM information_schema.TABLE_CONSTRAINTS t
JOIN information_schema.KEY_COLUMN_USAGE k
  ON t.CONSTRAINT_NAME = k.CONSTRAINT_NAME
 AND t.TABLE_SCHEMA = k.TABLE_SCHEMA
 AND t.TABLE_NAME = k.TABLE_NAME
WHERE t.CONSTRAINT_TYPE = 'PRIMARY KEY'
  AND t.TABLE_SCHEMA = 'sakila'
ORDER BY k.TABLE_NAME, k.ORDINAL_POSITION;
